### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by EliotBelinsky** [comment]
<h3>Character</h3>
                            <p class="tags small">AMBITIOUS HONEST ADJUSTED CALM RESERVED COMPETITIVE SOCIABLE AIMED
                                CONFIDENT LAZY RELIABLE</p>

**Comment by EliotBelinsky** [comment]
<section>
                                <h3>Languages</h3>
                                <p class="tags small">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span> &#x1f1f7;&#x1f1fa;
                                    <span>РУССКИЙ</span> <span class="language" lang="en">&#x1f1fa;&#x1f1f8;
                                        ENGLISH</span>
                                </p>
                            </section>
                            <section>
                                <h3>SKILLS</h3>
                                <p class="tags small">JAVA PYTHON GIT WINDOWS UBUNTU HTML/CSS/JS ADOBE PHOTOSHOP ADOBE
                                    PREMIERE PRO ADOBE AUDITION MICROSOFT OFICE GUITAR PIANO UKULELE ORGANIZING TIME
                                    MANAGEMENT
                                    PROBLEM-SOLVNG PUBLIC SPEAKING FLEXIBILITY CREATIVITY TEAMWORK SKILLS
                                </p>

                            </section>
                            <section>
                                <h3>Likes&#x1f603;</h3>
                                <p class="tags small">SAD SONGS GUITAR DIFFERENT MUSIC COVERS ON YOUTUBE PIANO BOOKS OF
                                    ANTI-UTOPIA <a
                                        href="https://www.youtube.com/watch?v=5g6cyyPjw_g&ab_channel=%D0%A2%D0%9E%D0%9F%D0%9B%D0%95%D0%A1"
                                        target="_blank">ТОПЛЕС</a>
                                    <a href="https://www.youtube.com/watch?v=hwzE8kQds-w&ab_channel=UtopiaShow"
                                        target="_blank">UTOPIA SHOW
                                    </a>
                                    <a href="https://www.youtube.com/watch?v=n-YhnxePIpM">GEO</a> YELLOW BLACK CATS
                                    DOGES HOT-DOGES PIZZA JAVA MATHEMATICS WORLD LITERATURE ENGLISH
                                </p>
                            </section>
                            <section>
                                <h3>Dislikes&#x1f61e;</h3>
                                <p class="tags small">PYTHON CREAM CAKES SALO ALCOHOL CIGARETTES HIGHER MATHEMATICS
                                    PHYSICS FELT-TIP PENS LIE TRAITORS</p>
                            </section>
                            <section>
                                <h3>Wants&#x1f97a;</h3>

                                <p class="tags small bulleted"><span class="tag">GAIN COMMERCIAL EXPERIENCE IN
                                        PROGRAMMING</span><span class="tag">RECORD MUSIC COVERS</span><span
                                        class="tag">GO HIKING</span><span class="tag">OBTAIN A
                                        MASTER'S DEGREE IN AN AMERICAN OR EUROPEAN UNIVERSITY</span><span
                                        class="tag"><span class="tag">IMPROVE ENGLISH</span>
                                        <span class="tag">ATTEND VOCAL LESSONS</span><span class="tag">BE HEALTH</span>
                                </p>
                            </section>

                            <section>
                                <h3>Education</h3>
                                <ul class="timeline">
                                    <li>
                                        <div><em>September 2009 &ndash; December 2017</em></div>
                                        <div>Volodymyr-Volynska <strong>School №5</strong> named after Anatoliy
                                            Korenevsky</div>
                                    </li>
                                    <li>
                                        <div><em>September 2012 &ndash; June 2018</em></div>
                                        <div>Volodymyr-Volyn Children's <strong>Music School</strong></div>
                                    </li>
                                    <li>
                                        <div><em>January 2017 &ndash; June 2020</em></div>
                                        <div>Volodymyr-Volynska <strong>Gymnasium</strong> named after Oleksandr
                                            Tsynkalovsky</div>
                                    </li>
                                    <li>
                                        <div><em>September 2020 &ndash; Now</em></div>
                                        <div> <strong>National Technical University of Ukraine</strong> “Igor Sikorsky
                                            Kyiv Polytechnic
                                            Institute”</div>
                                    </li>
                                </ul>

**Comment by tarastarasyuk** [comment]
Good job!
