### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by EliotBelinsky** [comment]
<h3>Experience</h3>
                            <ul class="timeline">
                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="project-4-dependencies" checked="">
                                        <label for="project-4-dependencies"
                                            class="summary"><strong>Recent</strong></label>
                                        <div>
                                            <small><strong>2021</strong></small>
                                            <ul>
                                                <li>trying to enter various academies for programmers</li>
                                                <li>not all…</li>
                                            </ul>

                                            <small><strong>2020</strong></small>
                                            <ul>
                                                <li>entered the National Technical University of Ukraine “Igor Sikorsky
                                                    Kyiv
                                                    Polytechnic Institute”</li>
                                                <li>graduated from high school with a gold medal</li>
                                                <li>started kickboxing</li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>

                                <ul>
                                    <li class="details">
                                        <input type="checkbox" id="project-4-dependencies" checked="">
                                        <label for="project-4-dependencies" class="summary"><strong>Back
                                                then</strong></label>
                                        <div>
                                            <small><strong>2019</strong></small>
                                            <ul>
                                                <li>was in English camp "Mascot"</li>
                                                <li>participated in the summit “БУМ”</li>
                                            </ul>

                                            <small><strong>2018</strong></small>
                                            <ul>
                                                <li>participated in trainings from “Active Citizens” by British Counsil
                                                </li>
                                                <li>was a participant of “School of Success” by Klitschko Foundation
                                                </li>
                                                <li>as part of delegations from my hometown visited Zwickau in German
                                                </li>
                                                <li>graduated from high school </li>
                                                <li>graduated from music school</li>
                                            </ul>

                                            <small><strong>2017</strong></small>
                                            <ul>
                                                <li>took part in the all-Ukrainian tournament on economics</li>
                                                <li>changed school</li>
                                            </ul>


                                            <small><strong>2014 - 2016</strong></small>
                                            <ul>
                                                <li>idk exactly when, but went hiking for 7 days in the Carpathians and
                                                    has
                                                    since fallen in love with the mountains</li>
                                                <li>idk how, but won 2nd place in international chess competitions</li>
                                            </ul>

                                            <small><strong>2013</strong></small>
                                            <ul>
                                                <li>climbed the highest mountain in Ukraine on my birthday (10 y.o.)
                                                </li>
                                            </ul>

                                        </div>
                                    </li>
                                </ul>
                            </ul>

                            <h3>Hobbies</h3>
                            <li class="highlighted">

                                <ul>
                                    <li>
                                        <strong>Fishing</strong>
                                        —
                                        as a child, my grandfather instilled in me a love for this business.
                                    </li>

                                    <li>
                                        <strong>Chess</strong>
                                        —
                                        one of the first clubs my dad took me to
                                    </li>
                                    <li>
                                        <strong>Guitar</strong>
                                        —
                                        a thing that plays an extremely important role in my life
                                    </li>
                                    <li>
                                        <strong>Economics</strong>
                                        —
                                        thanks to my dad I started studying this subject and it is really important
                                    </li>
                                    <li>
                                        <strong>Basketball </strong>
                                        —
                                        well, I really liked this game
                                    </li>
                                    <li>
                                        <strong>Singing </strong>
                                        —
                                        one more thing that plays an extremely important role in my life
                                    </li>
                                    <li>
                                        <strong>Kickboxing </strong>
                                        —
                                        a sport that made me feel my body differently
                                    </li>
                                    <li>
                                        <strong>Programmmmmming </strong>
                                        —
                                        exactly what I see myself now and soon
                                    </li>

                                </ul>
                            </li>
