### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by EliotBelinsky** [comment]
<h1 class="name">Donald Trump</h1>
                                    <div class="job">President of United States of America</div>
                                    <ul class="contacts">
                                        <li>
                                          <a href="https://www.fb.com/DonaldTrump" rel="author" target="_blank" class="facebook">
                                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                              <path d="M448 56.7v398.5c0 13.7-11.1 24.7-24.7 24.7H309.1V306.5h58.2l8.7-67.6h-67v-43.2c0-19.6 5.4-32.9 33.5-32.9h35.8v-60.5c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4v67.6h58.4V480H24.7C11.1 480 0 468.9 0 455.3V56.7C0 43.1 11.1 32 24.7 32h398.5c13.7 0 24.8 11.1 24.8 24.7z"></path>
                                            </svg>
                                            <span>DonaldTrump</span>
                                          </a>
                                        </li>
                                        <li>
                                          <a href="realDonaldTrump@whitehouse.gov" rel="author" target="_blank" class="mail">
                                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                              <path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path>
                                            </svg>
                                            <span>realDonaldTrump@whitehouse.gov</span>
                                          </a>
                                        </li>
                                        <li>
                                          <a href="https://twitter.com/realDonaldTrump" rel="author" target="_blank" class="twitter">
                                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                                              <path class="foreground"  d="m 16.00026,3.0388625 c -0.58865,0.2610694 -1.22138,0.4374284 -1.88531,0.51677 0.67769,-0.4061557 1.19826,-1.0492863 1.4433,-1.8156882 -0.63433,0.3761626 -1.33682,0.6492191 -2.08459,0.796395 C 12.87493,1.8984774 12.0218,1.5 11.07762,1.5 9.2648,1.5 7.79493,2.9693587 7.79493,4.7817676 c 0,0.2572203 0.029,0.5077321 0.085,0.7479163 C 5.15173,5.3928357 2.73298,4.0862392 1.11391,2.1006705 0.83135,2.5853679 0.66942,3.1490869 0.66942,3.7505572 c 0,1.1386255 0.57953,2.1431321 1.46035,2.7316454 C 1.59168,6.4652065 1.08551,6.3175109 0.64294,6.071728 c -3.7e-4,0.013697 -3.7e-4,0.027394 -3.7e-4,0.04129 0,1.5900606 1.13154,2.9164125 2.63324,3.2181024 C 3.00037,9.4061034 2.71036,9.446214 2.411,9.446214 c -0.21153,0 -0.41713,-0.020595 -0.61761,-0.058886 0.41776,1.303797 1.63002,2.252636 3.06653,2.27903 -1.12346,0.880286 -2.53884,1.404974 -4.07687,1.404974 -0.26496,0 -0.52625,-0.0156 -0.78305,-0.04589 C 1.45274,13.956676 3.17821,14.5 5.032,14.5 c 6.03793,0 9.33982,-5.0007583 9.33982,-9.3377308 0,-0.1422969 -0.003,-0.283784 -0.01,-0.4246313 0.64129,-0.4626226 1.19778,-1.0405783 1.63787,-1.6987554 z"/>
                                            </svg>
                                            <span>realDonaldTrump</span>
                                          </a>
                                        </li>
                                        <li>
                                          <a href="https://www.instagram.com/realDonaldTrump/" rel="author" target="_blank" class="instagram">
                                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="2 2 20 20" style="fill:#000000;">
                                              <path d="M 3 3 L 3 21 L 21 21 L 21 3 L 3 3 z M 18 5 C 18.552 5 19 5.448 19 6 C 19 6.552 18.552 7 18 7 C 17.448 7 17 6.552 17 6 C 17 5.448 17.448 5 18 5 z M 12 7 C 14.761 7 17 9.239 17 12 C 17 14.761 14.761 17 12 17 C 9.239 17 7 14.761 7 12 C 7 9.239 9.239 7 12 7 z M 12 9 A 3 3 0 0 0 9 12 A 3 3 0 0 0 12 15 A 3 3 0 0 0 15 12 A 3 3 0 0 0 12 9 z"></path>
                                            </svg>
                                            <span>realDonaldTrump</span>
                                          </a>
                                        </li>
                                    </ul>
