### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by EliotBelinsky** [comment]
**Experience**
<h3>Experience</h3>
                              
                              <ul>
        											  <li class="details">
                                  <input type="checkbox" id="project-4-dependencies" checked>
          												<label for="project-4-dependencies" class="summary"><strong>Recent</strong></label>
          												<div>
                                    <small><strong>2017</strong></small>
                                    <p>Became 45th president of the United States</p>
                                    <small><strong>2016</strong></small>
                                    <p>Won election race with 77 votes more than <a href="https://en.wikipedia.org/wiki/Bill_Clinton">Clinton</a>, yippe-kee-yay!</p>
                                    <small><strong>2015</strong></small>
                                    <p>Became the most important Republican nominating for presidential election run</p>
                                    <small><strong>2009</strong></small>
                                    <p>Changed my mind and became Republican again</p>
                                    <small><strong>2005</strong></small>
                                    <p>Started Trump University with Michael Sexton and Jonathan Spitalny: no grades, certificates and other bureaucracy, but program offered courses in real estate, asset management entrepreneurship, and wealth creation. 98% students gave positive reviews while studying, however some of these ungrateful gringos filed lawsuits against Trump University after the course. I had to pay $25 million to settle that...</p>
                                    <small><strong>2002</strong></small>
                                    <p>Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the Trump Park Avenue. I sure do like my surname!</p>
                                    <small><strong>2001</strong></small>
                                    <p>Completed <a href="https://en.wikipedia.org/wiki/Trump_World_Tower" target="_blank">Trump World Tower</a> and joined the Democratic Party</p>
          												</div>
        											  </li>
        										  </ul>
                              
                              <ul>
        											  <li class="details">
                                  <input type="checkbox" id="project-4-dependencies">
          												<label for="project-4-dependencies" class="summary"><strong>Back then</strong></label>
          												<div>
                                    <small><strong>1999</strong></small>
                                    <p>Started buying golf courses. They are very cheap, I have 18 of them now in USA and abroad! Also switched to the Reform Party that year</p>
                                    <small><strong>1997</strong></small>
                                    <p>Began a multi-building development along the Hudson River, which was named Trump Place. Me and the other investors sold our shares for $1.8 billion and that was then the biggest residential sale in the history of New York City</p>
                                    <small><strong>1996</strong></small>
                                    <p>Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building</p>
                                    <small><strong>1994</strong></small>
                                    <p>Refurbished the Gulf and Western Building on Columbus Circle, turned it into a 44-story luxury property known as Trump International Hotel and Tower</p>
                                    <small><strong>1989 ― 1992</strong></small>
                                    <p>Ran a second hand airline called Trump Shuttle. What a waste of money, I had to sell it, now it is American Airlines Shuttle, btw</p>
                                    <small><strong>1989, 1990</strong></small>
                                    <p>Learned about Tour de France and decided to hold my very own Tour de Trump. Is America not great enough for that cycling competition?</p>
                                    <small><strong>1988</strong></small>
                                    <p>Acquired the Plaza Hotel in Manhattan for $407 million, invested $50 million to restore the building and boosted it from three-star to four-star hotel (I called it "the Mona Lisa" and sold it for a lot of cash in 1995)</p>
                                    <small><strong>1987</strong></small>
                                    <p>Registered as a Republican</p>
                                    <small><strong>1985</strong></small>
                                    <p>I bought the Mar-a-Lago estate in Palm Beach and turned it into a private club.You can join if you pay $200K initiation fee (and there is another annual fee for members, it is very expensive to be rich). That year I also opened a casino called Trump Castle. My wife Ivana became a manager, because she is another Trump!</p>
                                    <small><strong>1983</strong></small>
                                    <p>I purchased New Jersey Generals, an American football team. I changed team's play schedule and filed an antitrust lawsuit against United States Football League, so NJG are not doing so good now, but back then they were great!</p>
                                    <small><strong>1980</strong></small>
                                    <p>Started developing the Trump Tower skyscraper in Manhattan, I payed a crew of undocumented Polish workers to demolish the historic Bonwit Teller store, including art deco features. All this to make architectural critic Paul Goldberger say in 1983 that the tower's atrium is "the most pleasant interior public space to be completed in New York in some years". At the same time I also started a repair job on the Wollman Rink in Central Park and completed the work in three months for $1.95 million, which was $775,000 less than the initial budget!</p>
          												</div>
        											  </li>
        										  </ul>
                              
                              <ul>
        											  <li class="details">
                                  <input type="checkbox" id="other">
          												<label for="other" class="summary"><strong>Way back then</strong></label>
          												<div>
                                      <small><strong>1978</strong></small>
                                      <p>Purchased a 50 percent stake in the derelict Commodore Hotel and turned it into the Grand Hyatt Hotel in 2 years of remodeling</p>
                                      <small><strong>1971</strong></small>
                                      <p>Was promoted to president of the company and renamed it The Trump Organization</p>
                                      <small><strong>1968</strong></small>
                                      <p>Began my career at my father's real estate development company, Elizabeth Trump & Son</p>
          												</div>
        											  </li>
        										  </ul>
                            <br>

**Comment by EliotBelinsky** [comment]
<h3>PERSONAL LIFE</h3>
                              <li class="highlighted">
                                <ul>
                                  <li>
                                  <strong><small>2006</small></strong>
                                  &mdash;
                                  <a href="https://en.wikipedia.org/wiki/Melania_Trump" target="_blank">Melania</a> gained United States citizenship and gave birth to our son, <a href="https://g.co/kgs/86V5oT">Barron</a>
                                  </li>
                                  <li>
                                  <strong><small>2005</small></strong>
                                  &mdash;
                                  Married her
                                  </li>
                                  <li>
                                  <strong><small>1998</small></strong>
                                  &mdash;
                                  Met my future third wife, Melania Knauss
                                  </li>
                                  <li>
                                  <strong><small>1999</small></strong>
                                  &mdash;
                                  Divorced Marla ¯_(ツ)_/¯
                                  </li>
                                  <li>
                                  <strong><small>1993</small></strong>
                                  &mdash;
                                  Married Marla and had a daughter, we named her Tiffany, because I like <a href="https://www.tiffany.com/" target="_blank">Tiffany & Company</a> jewellery as well
                                  </li>
                                  <li>
                                  <strong><small>1992</small></strong>
                                  &mdash;
                                  Started affair with Marla Maples, so I had to divorce. God knows I love nice women, I love them all!
                                  </li>
                                  <li>
                                  <strong><small>1984</small></strong>
                                  &mdash;
                                  Birth of <a href="https://en.wikipedia.org/wiki/Eric_Trump" target="_blank">Eric Trump</a>
                                  </li>
                                  <li>
                                  <strong><small>1982</small></strong>
                                  &mdash;
                                  Birth of <a href="https://en.wikipedia.org/wiki/Ivanka_Trump" target="_blank">Ivanka Trump</a>
                                  </li>
                                  <li>
                                  <strong><small>1977</small></strong>
                                  &mdash;
                                  My first son is born. I called him <a href="https://en.wikipedia.org/wiki/Donald_Trump_Jr" target="_blank">Donald</a>, of course!
                                  </li>
                                  <li>
                                  <strong><small>1977</small></strong>
                                  &mdash;
                                  Married Czech model Ivana Zelníčková
                                  </li>
                              </ul>
                            </li>
                            <br>

**Comment by EliotBelinsky** [comment]
<h3>MEDIA CAREER</h3>
                            
                              <ul>
                                <li class="details">
                                  <input type="checkbox" id="project-4-dependencies">
                                  <label for="project-4-dependencies" class="summary"><strong>21<sup>th</sup> century</strong></label>
                                  <div>
                                    <small><strong>2019</strong></small>
                                    <p>Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"</p>
                                    <small><strong>2015</strong></small>
                                    <p>Published a book "Crippled America: How to Make America Great Again"</p>
                                    <small><strong>2011</strong></small>
                                      <ul>
                                        <li></li>
                                        <li><p>Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver</p></li>
                                        <li><p>Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki</p></li>
                                        <li><p>Published a book "Trump Tower" in coauthorship with Jeffrey Robinson</p></li>
                                      </ul>
                                      <br>
                                    <small><strong>2009</strong></small>
                                    <p>Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver</p>
                                    <small><strong>2008</strong></small>
                                    <p>Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver</p>
                                    <small><strong>2007</strong></small>
                                      <ul>
                                        <li></li>
                                        <li><p>Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker</p></li>
                                        <li><p>Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant</p></li>
                                      </ul>
                                      <br>
                                    <small><strong>2006</strong></small>
                                      <ul>
                                        <li></li>
                                        <li><p>Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki</p></li>
                                        <li><p>Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"</p></li>
                                        <li><p>Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"</p></li>
                                        <li><p>Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver</p></li>
                                      </ul>
                                      <br>
                                    <small><strong>2005</strong></small>
                                      <ul>
                                        <li></li>
                                        <li><p>Published a book "The Best Golf Advice I Ever Received"</p></li>
                                        <li><p>Performed a song with Megan Mullally at the 57th Primetime Emmy Awards</p></li>
                                      </ul>
                                      <br>
                                    <small><strong>2004 ― 2008</strong></small>
                                    <p>Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)</p>
                                    <small><strong>2004</strong></small>
                                      <ul>
                                        <li></li>
                                        <li><p>Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver</p></li>
                                        <li><p>Published a book "The Way to the Top: The Best Business Advice I Ever Received"</p></li>
                                        <li><p>Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver</p></li>
                                      </ul>
                                      <br>
                                    <small><strong>2003 ― 2015</strong></small>
                                    <p>Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"</p>
                                    <small><strong>2000</strong></small>
                                    <p>Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett</p>
                                  </div>
                                </li>
                              </ul>
                            
                              <ul>
                                <li class="details">
                                  <input type="checkbox" id="project-4-dependencies" checked>
                                  <label for="project-4-dependencies" class="summary"><strong>20<sup>th</sup> century</strong></label>
                                  <div>
                                    <small><strong>1997</strong></small>
                                    <p>Published a book "Trump: The Art of the Comeback" in coauthorship with <a href="https://en.wikipedia.org/wiki/Kate_Bohner" target="_blank">Kate Bohner</a></p>
                                    <small><strong>1991</strong></small>
                                    <p>Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"</p>
                                    <small><strong>1990</strong></small>
                                    <p>Published a book "Trump: Surviving at the Top" in coauthorship with <a href="https://twitter.com/charlesleerhsen" target="_blank">Charles Leerhsen</a></p>
                                    <small><strong>1987</strong></small>
                                    <p>Published a book "Trump: The Art of the Deal" in coauthorship with <a href="https://en.wikipedia.org/wiki/Tony_Schwartz_(author)" target="_blank">Tony Shwartz</a></p>
                                  </div>
                                </li>
                              </ul>
                            <br>

**Comment by tarastarasyuk** [comment]
Wow!!!
