### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by EliotBelinsky** [comment]
Contacts:
+38 (093) 1153104
skype:taras_tarasyuk
https://github.com/tarastarasyuk
mail:worktarasyuk@gmail.com
https://www.fb.com/tarastarasyuk
