### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by EliotBelinsky** [comment]
<section>
                              <h3>Languages</h3>
                              <p class="tags small">
                                <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a>
                                <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                            </section>
                            
                            <section>
                              <h3>Skills</h3>
                              <p class="tags small bulleted">
                                <span class="tag">NEGOTIATING</span>
                                <span class="tag">COUNTING</span>
                                <span class="tag">REMODELING</span>
                                <span class="tag">WRITING</span>
                                <span class="tag">ACING</span>
                                <span class="tag">SINGING</span>
                                <span class="tag">REPORTING</span>
                                <span class="tag">INCORPORATING</span>
                                <span class="tag">SELLING</span>
                                <span class="tag">ADVERTISING</span>
                                <span class="tag">HOSTING</span>
                                <span class="tag">COMPETING</span>
                                <span class="tag"><strong>TWITTING</strong></span>
                                <span class="tag">PARENTING</span>
                                <span class="tag">GAMBLING</span>
                                <span class="tag">DATING</span>
                                <span class="tag">SUING</span>
                                <span class="tag">ORGANIZING</span>
                                <span class="tag">FUNDING</span>
                                <span class="tag">DEBATING</span>
                                <span class="tag">ADVISING</span>
                                <span class="tag">PRESBYTERIANING</span>
                              </p>
                            </section>
                            
                            <section>
                              <h3>Character</h3>
                              <p class="tags small">ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING</p>
                            </section>
                            
                            <section>
                              <h3>Likes&#x1f603;</h3>
                              <p class="tags small"><a href="https://www.youtube.com/watch?v=u_aLESDql1U&ab_channel=VICENews" target="_blank">BILLIONS</a> FILET-O-FISH BIG MAC <a href="https://www.youtube.com/watch?v=RDrfE9I8_hs" target="_blank">CHINA</a> QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY <a href="https://www.youtube.com/watch?v=0f9ysmciWUk&ab_channel=VICENews" target="_blank">[1]</a> <a href="https://www.youtube.com/watch?v=TTdmKaXAfAs&ab_channel=WashingtonPost" target="_blank">[2]</a></p>
                            </section>
                            
                            <section>
                              <h3>Dislikes&#x1f61e;</h3>
                              <p class="tags small">DOGS MEDIA <a href="https://edition.cnn.com/" target="_blank">CNN</a> GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS</p>
                            </section>
                            
                            <section>
                              <h3>Wants&#x1f97a;</h3>
                              <p class="tags small bulleted">BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO GOLF MORE OFTEN WIN ALL THE COURT SUITS</p>
                            </section>
                            
                            <section>
                              <h3>Education</h3>
                              <ul class="timeline">
                                <li>
                                  <div><em>2011</em></div>
                                  <div>Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!</div>
                                </li>
                                <li class="highlighted">
                                  <div><em>1966</em></div>
                                  <ul>
                                    <li class="details">
                                      <input type="checkbox" id="project-4-dependencies" checked>
                                      <label for="project-4-dependencies" class="summary"><a href="https://www.wharton.upenn.edu/" target="_blank">Wharton School</a></label>
                                      <div>Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics</div>
                                    </li>
                                  </ul>
                                </li>
                                <li>
                                  <div><em>1964</em></div>
                                  <ul>
                                    <li class="details">
                                      <input type="checkbox" id="project-4-dependencies" checked>
                                      <label for="project-4-dependencies" class="summary"><a href="https://www.fordham.edu/" target="_blank">Fordham University</a></label>
                                      <div>Started studying in Fordham University</div>
                                    </li>
                                  </ul>
                                </li>
                                <li class="highlighted">
                                  <div><em>1959</em></div>
                                  <ul>
                                    <li class="details">
                                      <input type="checkbox" id="project-4-dependencies" checked>
                                      <label for="project-4-dependencies" class="summary"><a href="https://www.nyma.org/" target="_blank">New York Military Academy</a></label>
                                      <div>Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission</div>
                                    </li>
                                  </ul>
                                </li>
                              </ul>
                            </section>
