### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by tarastarasyuk** [tarastarasyuk/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by EliotBelinsky** [comment]
Hello! I’m a 17 y.o. boy who study in KPI and wants to became Full Stack Developer

**Comment by tarastarasyuk** [comment]
Thx
